### ISSUE TITLE
Promisify

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/website-popup#2]
I looked into promisifying this module but it's harder then it might look because at the moment it returns the `cp.kill` function as result and you can respond in the callback when that function was fired programatically. But it looks like this is not really possible when I want to return a promise.

Any ideas on a new API or am I missing something?

**Comment by sindresorhus** [comment]
I don't see the point in being able to close it after a timeout. Instead, we can pass the kill method as the first argument in the promise instead. In the docs I would call it `close` and not `kill`.

**Comment by SamVerschueren** [comment]
👍

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/website-popup/commit/4dd94ca30dc0781e72a849873a5ac094653a03b8.
